#!/usr/bin/env python3
import requests

resp = requests.get( 'https://m.news.naver.com/home.nhn' )
# resp.raise_for_status()

if (resp.status_code == requests.codes.ok):
    html = resp.text
    print(html)
